In [94]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.optim as optim 

In [107]:
model = nn.Linear(32, 32, bias=False)
inp = torch.ones(8, 32)
out = torch.ones(8, 32) * 2

out_grad = None
def _backward_hook(model, grad_input, grad_output):
    model.out_grad = grad_output[0]
    
model.register_backward_hook(_backward_hook)

In [108]:
crit = nn.MSELoss()
optim = torch.optim.SGD(model.parameters(), lr=0.1)

In [109]:
for i in range(20):
    optim.zero_grad()
    pred = model(inp)
    loss = crit(pred, out)
    loss.backward()
    print (pred.mean().item(), model.out_grad.mean().item(), (pred - model.out_grad).mean().item())
    optim.step()

0.07741253077983856 -0.015020214021205902 0.09243273735046387
0.4619300663471222 -0.012016171589493752 0.473946213722229
0.7695440649986267 -0.009612937457859516 0.7791569828987122
1.0156352519989014 -0.007690349593758583 1.0233255624771118
1.212508201599121 -0.006152280140668154 1.2186603546142578
1.3700065612792969 -0.004921823740005493 1.37492835521698
1.4960051774978638 -0.003937459085136652 1.4999427795410156
1.5968042612075806 -0.003149967407807708 1.5999541282653809
1.6774433851242065 -0.002519973088055849 1.67996346950531
1.7419546842575073 -0.0020159785635769367 1.7439706325531006
1.7935636043548584 -0.0016127832932397723 1.795176386833191
1.8348510265350342 -0.0012902264716103673 1.8361412286758423
1.8678808212280273 -0.00103218131698668 1.868912935256958
1.8943045139312744 -0.0008257446461357176 1.8951303958892822
1.9154436588287354 -0.0006605959497392178 1.9161043167114258
1.9323549270629883 -0.0005284767830744386 1.9328832626342773
1.945884108543396 -0.00042278142063878477

In [110]:
pred[0]

tensor([1.9774, 1.9783, 1.9675, 1.9674, 1.9720, 1.9617, 1.9647, 1.9778, 1.9661,
        1.9810, 1.9684, 1.9613, 1.9627, 1.9669, 1.9818, 1.9865, 1.9891, 1.9795,
        1.9632, 1.9783, 1.9812, 1.9743, 1.9675, 1.9655, 1.9643, 1.9693, 1.9824,
        1.9648, 1.9728, 1.9693, 1.9688, 1.9818], grad_fn=<SelectBackward>)

In [111]:
model.out_grad[0]

tensor([-1.7689e-04, -1.6973e-04, -2.5408e-04, -2.5471e-04, -2.1847e-04,
        -2.9944e-04, -2.7550e-04, -1.7320e-04, -2.6511e-04, -1.4852e-04,
        -2.4683e-04, -3.0221e-04, -2.9153e-04, -2.5825e-04, -1.4250e-04,
        -1.0545e-04, -8.5535e-05, -1.6012e-04, -2.8771e-04, -1.6986e-04,
        -1.4719e-04, -2.0094e-04, -2.5384e-04, -2.6954e-04, -2.7881e-04,
        -2.3971e-04, -1.3757e-04, -2.7537e-04, -2.1265e-04, -2.3963e-04,
        -2.4372e-04, -1.4223e-04])

In [112]:
(pred - model.out_grad)[0]

tensor([1.9775, 1.9784, 1.9677, 1.9677, 1.9723, 1.9620, 1.9650, 1.9780, 1.9663,
        1.9811, 1.9687, 1.9616, 1.9630, 1.9672, 1.9819, 1.9866, 1.9891, 1.9797,
        1.9635, 1.9784, 1.9813, 1.9745, 1.9678, 1.9658, 1.9646, 1.9696, 1.9825,
        1.9650, 1.9730, 1.9696, 1.9690, 1.9819], grad_fn=<SelectBackward>)